/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 08 18:55:04 GMT 2018
 */

package evo.com.strman;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.strman.StrmanAutoTestPart1;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StrmanAutoTestPart1_ESTest extends StrmanAutoTestPart1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      String string0 = StrmanAutoTestPart1.append("", stringArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[8];
      // Undeclared exception!
      try { 
        StrmanAutoTestPart1.appendArray((String) null, stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 'value' should be not null.
         //
         verifyException("com.strman.StrmanAutoTestPart1", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String string0 = StrmanAutoTestPart1.appendArray("", stringArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[8];
      String string0 = StrmanAutoTestPart1.appendArray("com.strman.StrmanAutoTestPart1", stringArray0);
      assertEquals("com.strman.StrmanAutoTestPart1nullnullnullnullnullnullnullnull", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        StrmanAutoTestPart1.append((String) null, stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 'value' should be not null.
         //
         verifyException("com.strman.StrmanAutoTestPart1", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[14];
      String string0 = StrmanAutoTestPart1.append("_Y ", stringArray0);
      assertEquals("_Y nullnullnullnullnullnullnullnullnullnullnullnullnullnull", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = StrmanAutoTestPart1.appendArray("", (String[]) null);
      assertEquals("", string0);
  }
}
